-- slit.light initial CMS schema
create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger language plpgsql security invoker set search_path = '' as $$
begin new.updated_at = now(); return new; end;
$$;

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.site_settings (
  id bigint generated by default as identity primary key,
  site_name text not null default '隙光 slit.light',
  logo_url text,
  favicon_url text,
  email text,
  line_name text,
  line_url text,
  instagram_url text,
  facebook_url text,
  phone text,
  meta_title text,
  meta_description text,
  og_image_url text,
  copyright text,
  company_information text,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.homepage_sections (
  id bigint generated by default as identity primary key,
  section_key text not null unique,
  title text,
  subtitle text,
  content text,
  image_url text,
  cta_text text,
  cta_url text,
  sort_order integer not null default 0,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pain_points (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  sort_order integer not null default 0,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.methods (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  image_url text,
  sort_order integer not null default 0,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  name text not null,
  subtitle text,
  description text,
  target_customer text,
  items jsonb not null default '[]'::jsonb check (jsonb_typeof(items) = 'array'),
  regular_price integer check (regular_price is null or regular_price >= 0),
  promo_price integer check (promo_price is null or promo_price >= 0),
  price_visible boolean not null default true,
  duration text,
  cta_text text,
  cta_url text,
  featured boolean not null default false,
  sort_order integer not null default 0,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cases (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  cover_image text,
  client_name text,
  client_type text,
  problem text,
  insight text,
  strategy text,
  execution text,
  result text,
  testimonial text,
  publish_status text not null default 'draft' check (publish_status in ('draft','published')),
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.faqs (
  id bigint generated by default as identity primary key,
  question text not null,
  answer text not null,
  sort_order integer not null default 0,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.inquiries (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 1 and 100),
  email text not null check (char_length(email) between 3 and 320),
  instagram text,
  line text,
  social_contact text,
  brand text,
  website text,
  problem_type text not null,
  problem_description text not null check (char_length(problem_description) between 1 and 5000),
  budget text,
  source text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  utm_term text,
  status text not null default 'new' check (status in ('new','contacted','discovery','quoted','active','completed','declined')),
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists services_public_order_idx on public.services(enabled, sort_order);
create index if not exists faqs_public_order_idx on public.faqs(enabled, sort_order);
create index if not exists cases_public_order_idx on public.cases(publish_status, sort_order);
create index if not exists inquiries_status_created_idx on public.inquiries(status, created_at desc);

do $$ declare table_name text; begin
  foreach table_name in array array['site_settings','homepage_sections','pain_points','methods','services','cases','faqs','inquiries'] loop
    execute format('drop trigger if exists set_%I_updated_at on public.%I', table_name, table_name);
    execute format('create trigger set_%I_updated_at before update on public.%I for each row execute function public.set_updated_at()', table_name, table_name);
  end loop;
end $$;

alter table public.admins enable row level security;
alter table public.site_settings enable row level security;
alter table public.homepage_sections enable row level security;
alter table public.pain_points enable row level security;
alter table public.methods enable row level security;
alter table public.services enable row level security;
alter table public.cases enable row level security;
alter table public.faqs enable row level security;
alter table public.inquiries enable row level security;

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = '' as $$
  select exists(select 1 from public.admins where user_id = auth.uid());
$$;
revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

create policy "admins can read own membership" on public.admins for select to authenticated using (user_id = auth.uid());

create policy "public reads published settings" on public.site_settings for select to anon, authenticated using (is_published or public.is_admin());
create policy "public reads enabled homepage" on public.homepage_sections for select to anon, authenticated using (enabled or public.is_admin());
create policy "public reads enabled pain points" on public.pain_points for select to anon, authenticated using (enabled or public.is_admin());
create policy "public reads enabled methods" on public.methods for select to anon, authenticated using (enabled or public.is_admin());
create policy "public reads enabled services" on public.services for select to anon, authenticated using (enabled or public.is_admin());
create policy "public reads published cases" on public.cases for select to anon, authenticated using (publish_status = 'published' or public.is_admin());
create policy "public reads enabled faqs" on public.faqs for select to anon, authenticated using (enabled or public.is_admin());

create policy "admins manage settings" on public.site_settings for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins manage homepage" on public.homepage_sections for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins manage pain points" on public.pain_points for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins manage methods" on public.methods for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins manage services" on public.services for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins manage cases" on public.cases for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins manage faqs" on public.faqs for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins read inquiries" on public.inquiries for select to authenticated using (public.is_admin());
create policy "admins update inquiries" on public.inquiries for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins delete inquiries" on public.inquiries for delete to authenticated using (public.is_admin());
create policy "public creates inquiries" on public.inquiries for insert to anon, authenticated with check (status = 'new' and note is null);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('site-images', 'site-images', true, 5242880, array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

create policy "public reads site images" on storage.objects for select to anon, authenticated using (bucket_id = 'site-images');
create policy "admins upload site images" on storage.objects for insert to authenticated with check (bucket_id = 'site-images' and public.is_admin());
create policy "admins update site images" on storage.objects for update to authenticated using (bucket_id = 'site-images' and public.is_admin()) with check (bucket_id = 'site-images' and public.is_admin());
create policy "admins delete site images" on storage.objects for delete to authenticated using (bucket_id = 'site-images' and public.is_admin());

insert into public.site_settings (id, site_name, email, meta_title, meta_description, copyright)
values (1, '隙光 slit.light', '35slit.light@gmail.com', '隙光 slit.light｜品牌內容策略・影像 IP 企劃', '協助有專業但說不清楚，以及有流量卻沒有形成詢問的人，整理品牌核心、內容定位與轉換卡點。', '© slit.light')
on conflict (id) do nothing;

insert into public.services (name, subtitle, description, target_customer, items, regular_price, promo_price, duration, cta_text, cta_url, featured, sort_order)
values
('內容診斷','先看清楚問題在哪裡，再決定下一步。','我不知道問題到底在哪裡。','已經有經營社群，但不知道問題在哪裡的人。','["事前資料檢視","60–90 分鐘一對一諮詢","現有內容診斷","核心問題整理","3 個優先改善方向","會後重點摘要"]',3500,2500,'一次 60–90 分鐘','告訴我你現在最卡的問題','#contact',false,1),
('IP 核心企劃','把專業與經驗，整理成清楚的內容定位。','我有專業、有想法，但不知道怎麼說清楚。','有專業、有想法，但不知道如何形成清楚內容定位的人。','["前期問卷","1–2 次深度訪談","IP／品牌核心梳理","目標客群與主要問題整理","差異化觀點","3–5 個內容主軸","10–15 個內容題目","一次修改"]',12000,8800,'約 7–10 個工作天','告訴我你現在最卡的問題','#contact',true,2),
('IP 內容轉換企劃','讓內容從被看見，接到信任與詢問。','已經有人看，但信任與詢問沒有接起來。','已經有流量，希望進一步建立信任、詢問與完整內容系統的人。','["IP 核心企劃全部內容","現有內容漏斗診斷","轉換卡點分析","內容與服務連結設計","20–30 個內容題目","3–5 支短影音企劃／腳本架構","CTA 建議","2–4 週執行追蹤"]',25000,18800,'約 2–4 週','告訴我你現在最卡的問題','#contact',false,3);

insert into public.faqs (question, answer, sort_order) values
('我還不知道自己的定位，可以找隙光嗎？','可以。定位不清楚正是適合透過訪談與核心挖掘一起整理的狀況，不需要先準備一套完整答案。',1),
('我沒有很多流量，也適合嗎？','適合。內容策略不只處理流量，更重要的是讓正確的人理解你的價值。',2),
('你們會直接幫我拍影片嗎？','隙光的核心服務是品牌內容與溝通策略。若需要拍攝或剪輯，可以依需求另外評估與報價。',3),
('這跟社群代操有什麼不同？','隙光聚焦在釐清你要說什麼、為誰而說，以及內容如何連接到理解、信任與詢問。',4),
('一次合作大概需要多久？','依方案約 60–90 分鐘、7–10 個工作天或 2–4 週，實際時間會依資料與討論節奏調整。',5),
('可以只做一次諮詢嗎？','可以。內容診斷就是一次性的服務。',6),
('需要準備什麼資料？','建議提供目前的社群、網站、服務介紹、過往內容，以及你觀察到的客戶問題。',7),
('線上還是實體？','以線上會議為主；若有實體訪談或拍攝需求，可再討論。',8),
('可以保證流量或成交嗎？','不能。觀看、成交與營收仍受到產品、市場、執行與銷售流程等因素影響。',9),
('做完之後我會拿到什麼？','依方案取得診斷摘要、品牌核心、目標客群、內容主軸、內容題目、轉換建議或腳本架構。',10),
('是否包含腳本？','IP 內容轉換企劃包含 3–5 支短影音企劃／腳本架構。完整逐字腳本可另行估價。',11),
('修改次數怎麼計算？','IP 核心企劃包含一次整體修改；新增方向或超出原範圍的內容會另行確認。',12),
('可以另外加購拍攝或剪輯嗎？','可以。完成策略與內容方向後，可依需要評估現場拍攝、剪輯或製作執行。',13);
